### ISSUE TITLE
unique

### ISSUE THREAD

**Issue by roblanf** [BronteES/Gender#1]
Hi Bronte,

In this line:

https://github.com/BronteES/Gender/blob/534a2c6c717c5948f434b84e08d6fc9ea5b7c596/GenderizeR.Code.R#L10

your use of unique isn't doing what you think it is. You need to save the output of `unique()` as a new object. E.g.

```
a = c(1, 1, 2, 3)
unique(a) # prints output to the screen
a # shows that a is still as before

b = unique(a) # fix it by saving to a new object
b # shows that b is now the unique values of a
a # a is still as before
```

**Comment by BronteES** [comment]
Fixed in https://github.com/BronteES/Gender/commit/92aa6865bdb3c288e6f56fd23f8cafc5b4c973c7
